# GENERATED by scripts/build_package.py from plugins/fin-macro/skills/macro-fx-industry-beta-shield/scripts/macro_fx_industry_beta_shield.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: macro-fx-industry-beta-shield (fin_skills.load('macro-fx-industry-beta-shield') returns its SKILL.md).

#!/usr/bin/env python3
"""Industry-Beta-Gated Macro & FX Transmission Shield (macro-fx-industry-beta-shield).

Converts a 1-D time-series macro or USD/CNH FX shock M_t into a genuine cross-sectional
equity alpha/shield score without look-ahead bias:

  1. Uniform Broadcast Defect:
     Broadcasting a raw macro series M_t equally across all stocks on day t has zero
     cross-sectional variance (Rank IC == 0) or, if added with a static positive sign,
     wrongly treats export-driven tech/manufacturing (beta_FX > 0) and domestic financials
     (beta_FX < 0) identically.
  2. Full-Sample Beta Look-Ahead Defect:
     Estimating stock i's macro/FX sensitivity beta_i over the full backtest sample [1..T]
     leaks future regime shifts into historical cross-sectional rankings.
  3. Causal Shrinkage Beta x Shock Shield:
     Estimates rolling causal sensitivity beta_{i, t-1} using strictly past data (<= t-1)
     and shrinks noisy single-stock betas toward the Leave-One-Out (j != i) industry peer
     beta prior before multiplying by today's Point-in-Time macro/FX shock M_t.
"""
from __future__ import annotations

import sys
from typing import Any

import numpy as np
import pandas as pd


def _resolve_ret_series(df: pd.DataFrame, ret_col: str) -> pd.Series:
    if ret_col in df.columns:
        return pd.to_numeric(df[ret_col], errors="coerce").fillna(0.0)
    for alt in ("stock_excess_return_1d", "return_1d", "ret_1d"):
        if alt in df.columns:
            return pd.to_numeric(df[alt], errors="coerce").fillna(0.0)
    raise TypeError(f"df is missing return column {ret_col!r}")


def _resolve_shock_series(df: pd.DataFrame, shock_col: str) -> pd.Series:
    if shock_col in df.columns:
        return pd.to_numeric(df[shock_col], errors="coerce").fillna(0.0)
    if "dxy_return_1d" in df.columns:
        dxy = pd.to_numeric(df["dxy_return_1d"], errors="coerce").fillna(0.0)
        vix_r = (
            pd.to_numeric(df["vix_return_1d"], errors="coerce").fillna(0.0)
            if "vix_return_1d" in df.columns
            else 0.0
        )
        us10y = (
            pd.to_numeric(df["us10y_change_1d"], errors="coerce").fillna(0.0)
            if "us10y_change_1d" in df.columns
            else 0.0
        )
        impulse = -np.tanh(dxy * 40.0) - 0.50 * np.tanh(vix_r * 10.0) - 0.50 * np.tanh(us10y * 10.0)
        return pd.Series(impulse, index=df.index, dtype=float)
    raise TypeError(f"df is missing macro/FX shock column {shock_col!r}")


def _resolve_industry_col(df: pd.DataFrame, industry_col: str) -> pd.Series:
    if industry_col in df.columns:
        return df[industry_col]
    for alt in ("supply_chain_cluster", "sector", "board_name"):
        if alt in df.columns:
            return df[alt]
    return pd.Series("ALL", index=df.index)


def estimate_causal_macro_fx_beta(
    df: pd.DataFrame,
    window: int = 20,
    min_periods: int = 5,
    shrinkage_lambda: float = 0.40,
    date_col: str = "date",
    symbol_col: str = "symbol",
    industry_col: str = "industry",
    ret_col: str = "ret_1d",
    shock_col: str = "macro_fx_shock",
) -> pd.Series:
    """Estimate strictly causal (<= t-1) stock sensitivity beta to macro/FX shocks with peer shrinkage."""
    if df.empty:
        return pd.Series(dtype=float)

    work = pd.DataFrame(
        {
            date_col: df[date_col],
            symbol_col: df[symbol_col],
            "_ind": _resolve_industry_col(df, industry_col),
            "_r": _resolve_ret_series(df, ret_col).to_numpy(dtype=np.float64),
            "_m": _resolve_shock_series(df, shock_col).to_numpy(dtype=np.float64),
            "_orig_pos": np.arange(len(df)),
        },
        index=df.index,
    )
    work.sort_values([symbol_col, date_col], inplace=True, kind="mergesort")

    grp_sym = work.groupby(symbol_col, sort=False)
    r_lag = grp_sym["_r"].shift(1)
    m_lag = grp_sym["_m"].shift(1)
    work["_r_lag"] = r_lag
    work["_m_lag"] = m_lag
    work["_rm_lag"] = r_lag * m_lag
    work["_m2_lag"] = m_lag * m_lag

    # Vectorized Cython rolling means over strictly lagged (<= t-1) quantities
    grp_roll = work.groupby(symbol_col, sort=False)
    roll_rm = grp_roll["_rm_lag"].rolling(window, min_periods=min_periods).mean().to_numpy(dtype=np.float64)
    roll_r = grp_roll["_r_lag"].rolling(window, min_periods=min_periods).mean().to_numpy(dtype=np.float64)
    roll_m = grp_roll["_m_lag"].rolling(window, min_periods=min_periods).mean().to_numpy(dtype=np.float64)
    roll_m2 = grp_roll["_m2_lag"].rolling(window, min_periods=min_periods).mean().to_numpy(dtype=np.float64)

    cov = np.nan_to_num(roll_rm - roll_r * roll_m, nan=0.0)
    var = np.clip(np.nan_to_num(roll_m2 - roll_m * roll_m, nan=1e-4), 1e-6, None)
    raw_beta = np.clip(cov / (var + 1e-5), -5.0, 5.0)
    work["_raw_beta"] = raw_beta

    # Leave-One-Out (j != i) industry peer beta on date t
    ind_grp = work.groupby([date_col, "_ind"], sort=False)["_raw_beta"]
    ind_sum = ind_grp.transform("sum").to_numpy(dtype=np.float64)
    ind_cnt = ind_grp.transform("count").to_numpy(dtype=np.float64)
    loo_ind_beta = np.where(
        ind_cnt > 1,
        (ind_sum - raw_beta) / np.maximum(ind_cnt - 1.0, 1.0),
        raw_beta,
    )
    shrunk_beta = (1.0 - shrinkage_lambda) * raw_beta + shrinkage_lambda * loo_ind_beta
    work["_beta"] = shrunk_beta
    work.sort_values("_orig_pos", inplace=True, kind="mergesort")
    return pd.Series(work["_beta"].to_numpy(dtype=float), index=df.index, name="causal_macro_fx_beta")


def compute_macro_fx_beta_shield(
    df: pd.DataFrame,
    window: int = 20,
    min_periods: int = 3,
    date_col: str = "date",
    symbol_col: str = "symbol",
    industry_col: str = "industry",
    ret_col: str = "ret_1d",
    shock_col: str = "macro_fx_shock",
    policy_col: str = "macro_policy_score",
) -> pd.Series:
    """Compute cross-sectional z-scored causal macro/FX beta-gated transmission shield."""
    if df.empty:
        return pd.Series(dtype=float)

    beta = estimate_causal_macro_fx_beta(
        df,
        window=window,
        min_periods=min_periods,
        date_col=date_col,
        symbol_col=symbol_col,
        industry_col=industry_col,
        ret_col=ret_col,
        shock_col=shock_col,
    )
    shock = _resolve_shock_series(df, shock_col)
    policy = (
        pd.to_numeric(df[policy_col], errors="coerce").fillna(0.0)
        if policy_col in df.columns
        else pd.Series(0.0, index=df.index)
    )
    raw_transmission = beta * (shock + 0.25 * policy)

    # When multimodal defensive quality & stress columns exist, combine beta*impulse with stress-gated resilience
    if "garp_valuation_quality" in df.columns and "vix_z30" in df.columns:
        vix_z = pd.to_numeric(df["vix_z30"], errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)
        dxy_abs = (
            np.abs(np.tanh(pd.to_numeric(df["dxy_return_1d"], errors="coerce").fillna(0.0).to_numpy(dtype=np.float64) * 40.0))
            if "dxy_return_1d" in df.columns
            else np.abs(shock.to_numpy(dtype=np.float64))
        )
        macro_stress = np.clip(0.50 * np.clip(vix_z, -1.5, 3.0) + 0.50 * dxy_abs + 0.50, 0.20, 2.50)
        garp = pd.to_numeric(df["garp_valuation_quality"], errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)
        smart = (
            pd.to_numeric(df["smart_vs_retail_divergence"], errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)
            if "smart_vs_retail_divergence" in df.columns
            else np.zeros(len(df), dtype=np.float64)
        )
        beta_abs = pd.Series(np.abs(beta.to_numpy(dtype=np.float64)), index=df.index)
        b_grp = beta_abs.groupby(df[date_col])
        beta_abs_z = ((beta_abs - b_grp.transform("mean")) / (b_grp.transform("std").replace(0.0, 1.0).fillna(1.0) + 1e-8)).fillna(0.0).to_numpy(dtype=np.float64)
        raw_transmission = pd.Series(
            0.30 * raw_transmission.to_numpy(dtype=np.float64)
            + macro_stress * (0.45 * garp + 0.30 * smart - 0.25 * beta_abs_z),
            index=df.index,
        )

    grp = raw_transmission.groupby(df[date_col])
    mean = grp.transform("mean")
    std = grp.transform("std").replace(0.0, 1.0).fillna(1.0)
    z = ((raw_transmission - mean) / (std + 1e-8)).clip(-3.5, 3.5).fillna(0.0)
    return pd.Series(z.to_numpy(dtype=float), index=df.index, name="macro_fx_industry_beta_shield")


def audit_macro_fx_beta_causality(
    df: pd.DataFrame,
    signal_col: str | None = None,
    date_col: str = "date",
    symbol_col: str = "symbol",
    industry_col: str = "industry",
    ret_col: str = "ret_1d",
    shock_col: str = "macro_fx_shock",
) -> dict[str, Any]:
    """Audit a macro/FX stock signal for uniform-broadcast defects and future-beta look-ahead."""
    if not isinstance(df, pd.DataFrame) or df.empty:
        raise TypeError("df must be a non-empty DataFrame")
    for c in (date_col, symbol_col):
        if c not in df.columns:
            raise TypeError(f"df is missing required column {c!r}")
    _ = _resolve_ret_series(df, ret_col)
    _ = _resolve_shock_series(df, shock_col)

    if signal_col is not None:
        if signal_col not in df.columns:
            raise TypeError(f"signal_col {signal_col!r} not in df.columns")
        sig = pd.to_numeric(df[signal_col], errors="coerce").fillna(0.0)
    else:
        sig = compute_macro_fx_beta_shield(
            df,
            date_col=date_col,
            symbol_col=symbol_col,
            industry_col=industry_col,
            ret_col=ret_col,
            shock_col=shock_col,
        )

    # Check 1: Cross-sectional dispersion on active dates (detects raw 1-D macro broadcast)
    cs_std = sig.groupby(df[date_col]).std().dropna()
    active_std = cs_std[cs_std.index > sorted(df[date_col].astype(str).unique())[min(3, len(cs_std) - 1)]]
    mean_cs_std = float(active_std.mean()) if len(active_std) else float(cs_std.mean() or 0.0)
    non_uniform_broadcast = bool(mean_cs_std > 1e-4)

    # Check 2: Future-bar perturbation invariance when computing causal shield
    dates = sorted(df[date_col].astype(str).unique())
    cut_idx = max(1, min(len(dates) - 2, int(len(dates) * 0.7)))
    cut_date = dates[cut_idx]
    past_mask = (df[date_col].astype(str) <= cut_date).to_numpy()

    pert = df.copy()
    r_col_actual = ret_col if ret_col in pert.columns else ("stock_excess_return_1d" if "stock_excess_return_1d" in pert.columns else "return_1d")
    s_col_actual = shock_col if shock_col in pert.columns else "dxy_return_1d"
    pert.loc[~past_mask, r_col_actual] = pd.to_numeric(pert.loc[~past_mask, r_col_actual], errors="coerce").fillna(0.0) + 5.0
    pert.loc[~past_mask, s_col_actual] = pd.to_numeric(pert.loc[~past_mask, s_col_actual], errors="coerce").fillna(0.0) + 2.0

    causal_base = compute_macro_fx_beta_shield(
        df, date_col=date_col, symbol_col=symbol_col, industry_col=industry_col, ret_col=ret_col, shock_col=shock_col
    ).to_numpy(dtype=float)
    causal_pert = compute_macro_fx_beta_shield(
        pert, date_col=date_col, symbol_col=symbol_col, industry_col=industry_col, ret_col=ret_col, shock_col=shock_col
    ).to_numpy(dtype=float)
    max_future_leak = float(np.nanmax(np.abs(causal_base[past_mask] - causal_pert[past_mask])))

    # If caller passed a precomputed signal_col, verify it correlates with causal shield and is not full-sample leaked
    caller_matches_causal = True
    if signal_col is not None and non_uniform_broadcast:
        corr = float(np.corrcoef(sig.to_numpy(dtype=float), causal_base)[0, 1]) if np.std(sig) > 1e-8 else 0.0
        caller_matches_causal = bool(corr >= 0.50)

    passed = bool(non_uniform_broadcast and (max_future_leak <= 1e-10) and caller_matches_causal)
    verdict = (
        "PASS: Macro-FX transmission shield has cross-sectional beta dispersion and zero future beta leakage."
        if passed
        else (
            "FAIL: Uniform 1-D macro broadcast detected (zero cross-sectional dispersion)"
            if not non_uniform_broadcast
            else "FAIL: Full-sample future beta look-ahead detected in macro/FX signal"
        )
    )
    return {
        "passed": passed,
        "verdict": verdict,
        "non_uniform_broadcast": non_uniform_broadcast,
        "mean_cross_sectional_std": round(mean_cs_std, 6),
        "max_future_leak_diff": float(max_future_leak),
        "caller_matches_causal": caller_matches_causal,
        "n_rows": int(len(df)),
        "n_dates": int(len(dates)),
    }


def _demo() -> int:
    rng = np.random.default_rng(11)
    dates = [f"2025-02-{d:02d}" for d in range(1, 16)]
    rows = []
    for d in dates:
        fx_shock = float(rng.normal(0.004, 0.01))
        for sym, ind, beta_true in (
            ("SH688981", "Semiconductor", 0.9),
            ("SH688041", "Semiconductor", 0.8),
            ("SH600036", "Bank", -0.4),
            ("SZ000001", "Bank", -0.35),
        ):
            rows.append({
                "date": d,
                "symbol": sym,
                "industry": ind,
                "ret_1d": float(beta_true * fx_shock + rng.normal(0.0, 0.01)),
                "macro_fx_shock": fx_shock,
            })
    df = pd.DataFrame(rows)
    df["macro_policy_score"] = np.cos(np.arange(len(df), dtype=float) * 0.25)
    df["shield"] = compute_macro_fx_beta_shield(df, window=5, min_periods=2)
    audit = audit_macro_fx_beta_causality(df, signal_col="shield")
    print(f"Macro-FX Industry Beta Shield demo: passed={audit['passed']} cs_std={audit['mean_cross_sectional_std']:.4f}")
    return 0 if audit["passed"] else 1


if __name__ == "__main__":
    sys.exit(_demo())
